import type { Destination, Package, Testimonial, RecentlyBooked, PressMention } from "@/types";

export const BUDGET_FILTERS = [
  { id: "all", label: "All Destinations" },
  { id: "under-50k", label: "Under ₹50K" },
  { id: "50k-1.5l", label: "₹50K to ₹1.5L" },
  { id: "1.5l-2.5l", label: "₹1.5L to ₹2.5L" },
  { id: "luxury", label: "Luxury" },
];

export const DURATION_FILTERS = [
  { id: "3-5", label: "3–5 Days" },
  { id: "6-9", label: "6–9 Days" },
  { id: "10+", label: "10+ Days" },
];

export const FILTER_TABS = [
  { id: "all", label: "All" },
  { id: "honeymoon", label: "Honeymoon" },
  { id: "family", label: "Family" },
  { id: "adventure", label: "Adventure" },
  { id: "beach", label: "Beach" },
  { id: "heritage", label: "Heritage" },
  { id: "budget", label: "Budget" },
];

export const NAV_LINKS = [
  { href: "/destinations", label: "Destinations" },
  { href: "/packages", label: "Holiday Packages" },
  { href: "/packages?type=honeymoon", label: "Honeymoon" },
  { href: "/packages?type=family", label: "Family" },
  { href: "/itinerary", label: "Plan with AI" },
];

export const STATS = [
  { value: "50K+", label: "Happy Travellers" },
  { value: "200+", label: "Destinations" },
  { value: "4.8★", label: "Average Rating" },
  { value: "24/7", label: "Travel Support" },
];

export const DESTINATIONS: Destination[] = [
  {
    id: "1",
    name: "Bali",
    country: "Indonesia",
    slug: "bali",
    cover_image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    description: "Tropical paradise with stunning temples, rice terraces, and beaches.",
    category: ["honeymoon", "beach", "adventure"],
    avg_price_inr: 45000,
    best_season: "Apr - Oct",
    visa_required: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Dubai",
    country: "UAE",
    slug: "dubai",
    cover_image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
    description: "Luxury shopping, ultramodern architecture, and desert adventures.",
    category: ["family", "luxury", "adventure"],
    avg_price_inr: 55000,
    best_season: "Nov - Mar",
    visa_required: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Thailand",
    country: "Thailand",
    slug: "thailand",
    cover_image: "https://images.unsplash.com/photo-1506665532589-32015fda9c33?w=800&q=80",
    description: "Golden temples, vibrant street food, and pristine islands.",
    category: ["budget", "beach", "adventure"],
    avg_price_inr: 35000,
    best_season: "Nov - Feb",
    visa_required: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Maldives",
    country: "Maldives",
    slug: "maldives",
    cover_image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80",
    description: "Overwater villas, crystal-clear lagoons, and world-class diving.",
    category: ["honeymoon", "beach", "luxury"],
    avg_price_inr: 85000,
    best_season: "Nov - Apr",
    visa_required: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Switzerland",
    country: "Switzerland",
    slug: "switzerland",
    cover_image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    description: "Alpine meadows, chocolate trails, and scenic train journeys.",
    category: ["family", "adventure", "heritage"],
    avg_price_inr: 120000,
    best_season: "Jun - Sep",
    visa_required: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Goa",
    country: "India",
    slug: "goa",
    cover_image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    description: "Sun-kissed beaches, Portuguese heritage, and vibrant nightlife.",
    category: ["budget", "beach", "adventure"],
    avg_price_inr: 15000,
    best_season: "Oct - Mar",
    visa_required: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Kerala",
    country: "India",
    slug: "kerala",
    cover_image: "https://images.unsplash.com/photo-1571670534812-2815935d3aaa?w=800&q=80",
    description: "Backwaters, Ayurveda retreats, and lush green landscapes.",
    category: ["family", "heritage", "budget"],
    avg_price_inr: 20000,
    best_season: "Sep - Mar",
    visa_required: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Singapore",
    country: "Singapore",
    slug: "singapore",
    cover_image: "https://images.unsplash.com/photo-1565967511849-646a97245621?w=800&q=80",
    description: "Futuristic gardens, hawker food culture, and family attractions.",
    category: ["family", "adventure"],
    avg_price_inr: 65000,
    best_season: "Feb - Apr",
    visa_required: false,
    created_at: new Date().toISOString(),
  },
];

export const PACKAGES: Package[] = [
  {
    id: "pkg-1",
    destination_id: "1",
    title: "Bali Honeymoon Escape — 6 Days",
    description: "Romantic getaway with private villa, spa sessions, and sunset dinners.",
    duration_days: 6,
    price_per_person: 52999,
    max_people: 2,
    inclusions: ["Flights", "4★ Hotel", "Breakfast", "Airport Transfer", "Spa Session"],
    exclusions: ["Lunch & Dinner", "Personal Expenses"],
    itinerary: null,
    images: ["https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80"],
    category: "honeymoon",
    badge: "hot",
    rating: 4.8,
    review_count: 234,
    created_at: new Date().toISOString(),
  },
  {
    id: "pkg-2",
    destination_id: "2",
    title: "Dubai Family Fun — 5 Days",
    description: "Burj Khalifa, Desert Safari, Aquaventure, and Dubai Mall experience.",
    duration_days: 5,
    price_per_person: 48999,
    max_people: 6,
    inclusions: ["Flights", "5★ Hotel", "Breakfast", "Desert Safari", "Burj Khalifa"],
    exclusions: ["Visa Fees", "Lunch & Dinner"],
    itinerary: null,
    images: ["https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80"],
    category: "family",
    badge: "deal",
    rating: 4.7,
    review_count: 189,
    created_at: new Date().toISOString(),
  },
  {
    id: "pkg-3",
    destination_id: "3",
    title: "Thailand Backpacker — 7 Days",
    description: "Bangkok street food, Chiang Mai temples, and Phuket beaches.",
    duration_days: 7,
    price_per_person: 32999,
    max_people: 10,
    inclusions: ["Flights", "3★ Hotels", "Breakfast", "Inter-city Transfer"],
    exclusions: ["Meals", "Activities"],
    itinerary: null,
    images: ["https://images.unsplash.com/photo-1506665532589-32015fda9c33?w=800&q=80"],
    category: "adventure",
    badge: "new",
    rating: 4.6,
    review_count: 156,
    created_at: new Date().toISOString(),
  },
  {
    id: "pkg-4",
    destination_id: "4",
    title: "Maldives Overwater Bliss — 4 Days",
    description: "Luxury overwater villa with all meals and water sports included.",
    duration_days: 4,
    price_per_person: 99999,
    max_people: 2,
    inclusions: ["Flights", "Overwater Villa", "All Meals", "Snorkeling", "Spa"],
    exclusions: ["Scuba Diving", "Alcohol"],
    itinerary: null,
    images: ["https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80"],
    category: "honeymoon",
    badge: "hot",
    rating: 4.9,
    review_count: 312,
    created_at: new Date().toISOString(),
  },
  {
    id: "pkg-5",
    destination_id: "6",
    title: "Goa Weekend Getaway — 3 Days",
    description: "Beach hopping, water sports, and Goan cuisine experience.",
    duration_days: 3,
    price_per_person: 8999,
    max_people: 8,
    inclusions: ["Hotel", "Breakfast", "Beach Activities", "Airport Transfer"],
    exclusions: ["Flights", "Lunch & Dinner"],
    itinerary: null,
    images: ["https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80"],
    category: "budget",
    badge: "deal",
    rating: 4.5,
    review_count: 421,
    created_at: new Date().toISOString(),
  },
  {
    id: "pkg-6",
    destination_id: "5",
    title: "Swiss Alps Adventure — 8 Days",
    description: "Jungfraujoch, Lucerne, Interlaken, and scenic train rides.",
    duration_days: 8,
    price_per_person: 145999,
    max_people: 4,
    inclusions: ["Flights", "4★ Hotels", "Breakfast", "Swiss Pass", "Excursions"],
    exclusions: ["Lunch & Dinner", "Personal Expenses"],
    itinerary: null,
    images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80"],
    category: "adventure",
    badge: "new",
    rating: 4.8,
    review_count: 98,
    created_at: new Date().toISOString(),
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Greeshma Jim",
    location: "Bhutan",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
    rating: 5,
    text: "Recently visited Bhutan via XOXO Travels and it was an absolutely wonderful experience. It was meticulously planned and they offered 24/7 customer care support, even checking in on us during the trip. Shoutout to the team for patiently handling all our queries!",
    destination: "Bhutan",
  },
  {
    id: "2",
    name: "Shweta Sharma",
    location: "Thailand",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    rating: 5,
    text: "A huge shout out to XOXO team for making my Thailand adventure smooth, hassle free and absolutely unforgettable. Travelling solo felt exciting, safe and incredibly easy.",
    destination: "Thailand",
  },
  {
    id: "3",
    name: "Ankit Mathur",
    location: "Thailand",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    rating: 5,
    text: "We had a wonderful trip to Thailand and overall were very satisfied with the arrangements. The itinerary was well planned, and the support provided throughout the journey was helpful and responsive. I would rate my overall trip experience 9/10.",
    destination: "Thailand",
  },
  {
    id: "4",
    name: "Neeta Omprakash",
    location: "Bali",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    rating: 5,
    text: "Our tour to Bali for five days was very well organised. The starting stage of planning the customised tour was very well done. We didn't have any difficulties anywhere. The choice of hotels was excellent.",
    destination: "Bali",
  },
];

export const RECENTLY_BOOKED: RecentlyBooked[] = [
  {
    id: "rb-1",
    userName: "Aziz",
    userInitial: "A",
    city: "Bengaluru",
    bookedAgo: "1hr ago",
    title: "Couple Escape: 5 Nights In Baku",
    cities: "Baku (5N)",
    tripType: "COUPLE",
    price: 55542,
    nights: 5,
    image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=400&q=80",
  },
  {
    id: "rb-2",
    userName: "Jay",
    userInitial: "J",
    city: "Chennai",
    bookedAgo: "2hr ago",
    title: "Couple Escape: 15 Nights In Como, Rome, Florence, Paris And Lucerne",
    cities: "Rome (3N) +4 more",
    tripType: "COUPLE",
    price: 165518,
    nights: 15,
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=400&q=80",
  },
  {
    id: "rb-3",
    userName: "Aishwarya",
    userInitial: "A",
    city: "Bengaluru",
    bookedAgo: "18hr ago",
    title: "Couple Holiday: 10 Nights In Split, Dubrovnik And Zagreb",
    cities: "Zagreb (3N) +2 more",
    tripType: "COUPLE",
    price: 157097,
    nights: 10,
    image: "https://images.unsplash.com/photo-1555992336-fb0d29498b13?w=400&q=80",
  },
  {
    id: "rb-4",
    userName: "Vicky",
    userInitial: "V",
    city: "Bengaluru",
    bookedAgo: "21hr ago",
    title: "Family Escape: 11 Nights In Grindelwald, Milan And Lucerne",
    cities: "Lucerne (3N) +2 more",
    tripType: "FAMILY",
    price: 90921,
    nights: 11,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&q=80",
  },
  {
    id: "rb-5",
    userName: "Kriti",
    userInitial: "K",
    city: "New Delhi",
    bookedAgo: "2hr ago",
    title: "Family Escape: 6 Nights In Da Nang And Hanoi",
    cities: "Da Nang (3N) +1 more",
    tripType: "FAMILY",
    price: 45610,
    nights: 6,
    image: "https://images.unsplash.com/photo-1583417319070-4a3323275041?w=400&q=80",
  },
  {
    id: "rb-6",
    userName: "Jatin",
    userInitial: "J",
    city: "Mumbai",
    bookedAgo: "21hr ago",
    title: "Friends Escape: 6 Nights In Bangkok And Pattaya",
    cities: "Pattaya (3N) +1 more",
    tripType: "FRIENDS",
    price: 35001,
    nights: 6,
    image: "https://images.unsplash.com/photo-1506665532589-32015fda9c33?w=400&q=80",
  },
];

export const PRESS_MENTIONS: PressMention[] = [
  {
    id: "1",
    source: "YourStory",
    quote: "XOXO Travels is carving a niche in personalised vacation planning and intends to become a one-stop shop for customised international holidays.",
    date: "Jun 08, 2019",
    url: "#",
  },
];

export const TRUST_PILLARS = [
  {
    title: "Customisation",
    description: "Every itinerary is built around your pace, style, and budget — not a one-size-fits-all template.",
  },
  {
    title: "Expertise",
    description: "Travel experts fine-tune every detail while our technology matches you with the best flights, stays, and activities.",
  },
  {
    title: "Service",
    description: "24×7 live chat support during your trip, transparent pricing, and zero hidden costs.",
  },
];

export const TOURISM_PARTNERS = [
  "Singapore Tourism",
  "Tourism Malaysia",
  "Tourism Australia",
  "Visit Dubai",
  "Incredible India",
  "Switzerland Tourism",
];

export const SOCIAL_FEATURES = [
  {
    title: "Solo Match",
    description: "Find travel buddies with similar interests and dates",
    href: "/match",
    icon: "Users",
    color: "bg-blue-50 text-primary",
  },
  {
    title: "Traveler Nearby",
    description: "Discover fellow travellers around you on the map",
    href: "/nearby",
    icon: "MapPin",
    color: "bg-orange-50 text-accent",
  },
  {
    title: "Group Trips",
    description: "Join or create group adventures with like-minded people",
    href: "/community",
    icon: "UsersRound",
    color: "bg-green-50 text-success",
  },
  {
    title: "Local Guides",
    description: "Book verified local guides for authentic experiences",
    href: "/guides",
    icon: "Compass",
    color: "bg-purple-50 text-purple-600",
  },
];
